//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTtable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTtable()
        {
            this.HFtable = new HashSet<HFtable>();
        }
    
        public int id { get; set; }
        public string gtZZ { get; set; }
        public string gtNR { get; set; }
        public string gtDay { get; set; }
        public int uID { get; set; }
        public int newID { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual newOne newOne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HFtable> HFtable { get; set; }
    }
}
